name: Delete Old Notes

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Call Notes Cleanup API
        run: |
          curl -X GET "${{ secrets.NOTES_CLEANUP_URL }}"
